[VALD_CONFIG]
client_id = "HDgfl7yGMdC1s6w=="
client_secret = "21patT6fiHd5KAkwCaiGytIXv62mVODc2eg="
tenant_id = "28887524-c9e0-4783-84a8-5d6ecc41c239"
token_url = "https://security.valdperformance.com/connect/token"
forcedecks_base_url = "https://prd-use-api-extforcedecks.valdperformance.com"
profiles_base_url = "https://prd-use-api-externalprofile.valdperformance.com"